In [1]:
import numpy as np
import cv2

In [2]:
black = np.zeros([150,200,1],'uint8')
cv2.imshow("Black",black)
print(black[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[0]


In [3]:
ones = np.ones([150,200,3],'uint8')
cv2.imshow("Ones",ones)
print(ones[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[1 1 1]


In [4]:
white = np.ones([150,200,3],'uint16')
white *= (2**16-1)
cv2.imshow("White",white)
print(white[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[65535 65535 65535]


In [5]:
color = ones.copy()
color[:,:] = (255,0,0)
cv2.imshow("Blue",color)
print(color[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[255   0   0]
